version: '3'
services:
    app:
        container_name: docker-angular
        restart: always
        build: .
        ports:
          - '80:80'
        links:
          - server
    server:
        container_name: docker-node
        restart: always
        build: ./server
        ports: 
           - '3000:3000'
    